version: '3'
services:
  RecReview:
    build:
      context: .
      dockerfile: Dockerfile
    image: ml
    container_name: RecReview
    volumes:
      - .:/home/ubuntu/project
    tty: true
    stdin_open: true
    #command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]